from . import general
from . import registration
from . import deep_links
from . import back_buttons
from . import courses
from . import homework
from . import profile
from . import quiz
from . import learning_centre
