# Generated by Django 3.2 on 2021-11-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonUrl',
        ),
    ]
