# Generated by Django 3.2 on 2021-11-01 15:05

import courses.utils.helpers
from django.db import migrations, models
import general.validators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_lessonurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learning_centre',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='autosend',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_message',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_message',
        ),
        migrations.RemoveField(
            model_name='course',
            name='week_size',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='has_homework',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image_file_id',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[general.validators.validate_hashtag], verbose_name='Хештег'),
        ),
        migrations.AddField(
            model_name='course',
            name='data',
            field=models.JSONField(blank=True, default=courses.utils.helpers.course_additional, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание дз'),
        ),
    ]
