# Generated by Django 3.2 on 2021-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211101_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='TEST DESCRIPTION', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
