# Generated by Django 3.2 on 2021-11-10 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('courses', '0005_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='form_pass_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Прохождения формы'),
        ),
    ]
