# Generated by Django 3.2 on 2021-11-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211110_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Видеоматериал Курса',
                'verbose_name_plural': 'Видеоматериалы Курса',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
