# Generated by Django 3.2 on 2021-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='set_priority_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый в спике бота'),
        ),
    ]
