# Generated by Django 3.2 on 2021-12-20 13:41

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def create_default_group(apps, schema_editor):
    CourseCategory = apps.get_model('courses', 'CourseCategory')

    CourseCategory.objects.create(name='Test Group')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_set_priority_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.RunPython(create_default_group, RunPython.noop),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
