# Generated by Django 3.2 on 2021-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211221_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rate_lesson_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение при оценке урока'),
        ),
    ]
