# Generated by Django 3.2 on 2021-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_rate_lesson_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='is_rated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
