# Generated by Django 3.2 on 2021-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_studentlesson_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'ТГ Профиль'), (2, 'Лид'), (3, 'Клиент'), (4, 'Контролируемый')], default=3, help_text='\nПримечание: при выборе Контролируемый, курс не откроется студенту автоматически.\nАдминистратору необходимо перейти в профиль студента и добавить курс студенту вручную \n', verbose_name='Доступ'),
        ),
    ]
