# Generated by Django 3.2 on 2021-12-27 14:57

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def create_default_group(apps, schema_editor):
    LessonCategory = apps.get_model('courses', 'LessonCategory')

    LessonCategory.objects.create(name='Test Group')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lessoncategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Группа курса', 'verbose_name_plural': 'Группы Курсов'},
        ),
        migrations.RunPython(create_default_group, RunPython.noop),

        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.lessoncategory', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursecategory', verbose_name='Группа'),
        ),
    ]
