# Generated by Django 3.2 on 2021-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Текст'),
        ),
    ]
