version: '3'

services:
  parcel-db:
    image: mariadb:10.3
    restart: on-failure
    environment:
      MYSQL_DATABASE: parcel
      MYSQL_USER: parcel
      MYSQL_PASSWORD: parcel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src:/parcel
    ports:
      - 3307:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./src:/parcel
    ports:
      - 8000:8000
    depends_on:
    - parcel-db
