version: '3'

services:
  parcel-db:
    image: mariadb:10.3
    restart: on-failure
    environment:
      MYSQL_DATABASE: parcel
      MYSQL_USER: parcel
      MYSQL_PASSWORD: parcel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src:/parcel
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3307:3306
  redis:
    image: redis:rc-alpine3.12
    restart: on-failure
    ports:
      - 6379:6379
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./src:/parcel
    ports:
      - 8000:8000
    depends_on:
    - parcel-db
    - redis
