version: '3'

services:
  db:
    image: gangstead/postgis:latest-arm
    restart: on-failure
    environment:
      POSTGRES_DB: parcel
      POSTGRES_USER: parcel
      POSTGRES_PASSWORD: parcel
    ports:
      - 15432:5432
  redis:
    image: redis:rc-alpine3.12
    restart: on-failure
    ports:
      - 6379:6379
  web:
    build: .
    image: parcel:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PYTHONPATH: /parcel
    volumes:
      - ./src:/parcel
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  celery:
    image: parcel
    build: .
    command: celery -A app worker -l info --pool=gevent --concurrency=10
    volumes:
      - ./src:/parcel
    depends_on:
      - web
      - redis
