version: '3'

services:
  parcel-db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: parcel
      POSTGRES_USER: parcel
      POSTGRES_PASSWORD: parcel
    ports:
      - 15432:5432
  redis:
    image: redis:rc-alpine3.12
    restart: on-failure
    ports:
      - 6379:6379
  web:
    build: .
    image: parcel-image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/parcel
    ports:
      - 8000:8000
    depends_on:
      - parcel-db
      - redis
  celery:
    image: parcel-image
    command: celery -A app worker -l info
    volumes:
      - ./src:/parcel
    depends_on:
      - redis
