# Generated by Django 3.2 on 2021-10-19 09:44

from django.db import migrations
from django.db.migrations import RunPython


def add_default_lang(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')

    for contact in Contact.objects.all():
        if not contact.data.get('lang'):
            contact.data['lang'] = '1'

            contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_lang, RunPython.noop),
    ]
