# Generated by Django 3.2 on 2021-09-21 12:35

import companies.utils.uploaders
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название Уч центра')),
                ('uz_title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Узбекская версия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=companies.utils.uploaders.lc_upload_directory, validators=[django.core.validators.validate_image_file_extension], verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(blank=True, help_text='При добавлении в боте появится кнопка ссылка', max_length=255, null=True, verbose_name='Ссылка')),
                ('slug', models.SlugField(unique=True, verbose_name='Поисковое поле')),
            ],
            options={
                'verbose_name': 'Уч центр',
                'verbose_name_plural': 'Уч центры',
            },
        ),
    ]
