# Generated by Django 3.2 on 2021-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_sendingreport'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='promo',
        ),
    ]
