# Generated by Django 3.2 on 2021-09-28 10:22

from django.db import migrations
from django.db.migrations import RunPython


def transition_students(apps, schema_editor):
    Student = apps.get_model('users', 'Student')
    Contact = apps.get_model('contacts', 'Contact')

    for student in Student.objects.all():
        try:
            contact = Contact.objects.get(tg_id=student.tg_id)
            student.contact = contact

        except Contact.DoesNotExist:
            contact = Contact.objects.create(
                first_name=student.first_name,
                last_name=student.last_name,
                tg_id=student.tg_id
            )
            student.contact = contact

        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_promo'),
    ]

    operations = [
        migrations.RunPython(transition_students, RunPython.noop),
    ]
