# Generated by Django 3.2 on 2021-09-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210928_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='blocked_bot',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tg_id',
        ),
    ]
