# Generated by Django 3.2 on 2021-10-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211011_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='language_type',
        ),
    ]
