# Generated by Django 3.2 on 2021-11-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_student_language_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='learning_centre',
            new_name='company',
        ),
    ]
