# Generated by Django 3.2 on 2021-04-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.student',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.student',),
        ),
    ]
