# Generated by Django 3.2 on 2021-05-04 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210503_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonurl',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
