# Generated by Django 3.2 on 2021-05-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_lessonurl_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_homework',
            field=models.BooleanField(default=False, verbose_name='Есть домашнее задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='', verbose_name='Видео к уроку'),
        ),
        migrations.DeleteModel(
            name='LessonCourse',
        ),
    ]
