# Generated by Django 3.2 on 2021-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210505_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chosen_field',
            field=models.CharField(choices=[('1', 'Game Development'), ('2', 'Web Development')], default=1, max_length=20, verbose_name='Желанная отрасль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='language_type',
            field=models.CharField(choices=[('1', 'Russian'), ('2', 'Uzbek')], default='1', max_length=20, verbose_name='Язык ученик'),
        ),
    ]
