# Generated by Django 3.2 on 2021-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210505_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='add_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сообщение для отправки студенту после добавления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language_type',
            field=models.CharField(choices=[('1', 'Russian'), ('2', 'Uzbek')], default='1', max_length=20, verbose_name='Язык ученика'),
        ),
    ]
