# Generated by Django 3.2 on 2021-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210506_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unique_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Инвайт код'),
        ),
    ]
