# Generated by Django 3.2 on 2021-05-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210507_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonurl',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='Студент'),
        ),
    ]
