# Generated by Django 3.2 on 2021-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_student_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='Урок начат'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_lesson_index',
            field=models.IntegerField(default=0, verbose_name='Последний посланный урок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='week_size',
            field=models.IntegerField(default=0, verbose_name='Количество уроков в неделю'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='invite_link',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Инвайт ссылка'),
        ),
    ]
