# Generated by Django 3.2 on 2021-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210511_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Homework description'),
        ),
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(through='dashboard.StudentLesson', to='dashboard.Lesson'),
        ),
    ]
