# Generated by Django 3.2 on 2021-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210511_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Homework description'),
        ),
    ]
