# Generated by Django 3.2 on 2021-05-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_stream_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
