# Generated by Django 3.2 on 2021-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_stream_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.stream', verbose_name='ID потока'),
        ),
    ]
