# Generated by Django 3.2 on 2021-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210512_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ManyToManyField(to='dashboard.Stream'),
        ),
    ]
