# Generated by Django 3.2 on 2021-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210512_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID группы'),
        ),
    ]
