# Generated by Django 3.2 on 2021-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_course_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='homework_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки дз'),
        ),
    ]
