# Generated by Django 3.2 on 2021-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_studentlesson_homework_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Курс закончен'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения урока'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='date_watched',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата дата просмотра урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Если вводится Chatid группы вам нужно создать группу, добавить туда бота, узнать её чат айди, и ввести его здесь. Боту надо дать админ права в группе чтобы он мог форвардить сообщения', null=True, verbose_name='Telegram ID'),
        ),
    ]
