# Generated by Django 3.2 on 2021-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20210518_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_lesson_index',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.IntegerField(default=0, verbose_name='Сколько уроков отправлять сразу при старте курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отсылки урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='week_size',
            field=models.IntegerField(default=0, verbose_name='Количество уроков в неделю'),
        ),
    ]
