# Generated by Django 3.2 on 2021-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210519_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сколько уроков отправлять сразу при старте курса'),
        ),
    ]
