# Generated by Django 3.2 on 2021-05-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_course_lesson_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
    ]
