# Generated by Django 3.2 on 2021-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Photo file ID'),
        ),
    ]
