# Generated by Django 3.2 on 2021-05-25 16:03

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_lesson_image_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_count',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата отсылки урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.lesson_upload_directory, validators=[dashboard.validators.validate_photo_extension], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to=dashboard.models.lesson_upload_directory, validators=[dashboard.validators.validate_video_extension], verbose_name='Видео к уроку'),
        ),
    ]
