# Generated by Django 3.2 on 2021-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20210525_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hashtag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Хештег'),
        ),
    ]
