# Generated by Django 3.2 on 2021-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20210527_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='autosend',
            field=models.BooleanField(default=False, verbose_name='Авто-отправка'),
        ),
    ]
