# Generated by Django 3.2 on 2021-06-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_course_autosend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlesson',
            old_name='date_received',
            new_name='date_sent',
        ),
    ]
