# Generated by Django 3.2 on 2021-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_studentlesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='chat_id',
            field=models.BigIntegerField(default=0, help_text='Если вводится Chatid группы вам нужно создать группу, добавить туда бота, узнать её чат айди, и ввести его здесь. Боту надо дать админ права в группе чтобы он мог форвардить сообщения', verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
