# Generated by Django 3.2 on 2021-06-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_course_chat_id'),
    ]

    operations = [
    ]
