# Generated by Django 3.2 on 2021-06-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20210617_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.categorytype', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='chosen_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.categorytype', verbose_name='Желанная отрасль'),
            preserve_default=False,
        ),
    ]
