# Generated by Django 3.2 on 2021-06-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20210617_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytype',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
