# Generated by Django 3.2 on 2021-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20210617_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytype',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='categorytype',
            name='uz_title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Узбекская версия'),
        ),
    ]
