# Generated by Django 3.2 on 2021-06-22 16:21

import django.db.models.deletion
from django.db import migrations, models

import dashboard.models
import dashboard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20210618_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('video', models.FileField(upload_to=dashboard.models.promo_upload_directory, validators=[dashboard.validators.validate_video_extension], verbose_name='Промо видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('counter', models.IntegerField(default=0, verbose_name='Подсчет просмотра')),
                ('registration_button', models.BooleanField(default=False, verbose_name='Кнопка регистрации')),
                ('link', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Инвайт ссылка')),
                ('notify_all', models.BooleanField(default=False, verbose_name='Уведомить всех')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.promotion', verbose_name='Из какого промо пришел'),
        ),
    ]
