# Generated by Django 3.2 on 2021-06-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20210622_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='notify_all',
        ),
    ]
