# Generated by Django 3.2 on 2021-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_promotion_notify_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='video_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Video file ID'),
        ),
    ]
