# Generated by Django 3.2 on 2021-06-23 15:13

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_promotion_video_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.promo_upload_directory, validators=[dashboard.validators.validate_photo_extension], verbose_name='Превью видео'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='thumbnail_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Video file ID'),
        ),
    ]
