# Generated by Django 3.2 on 2021-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_alter_promotion_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='thumbnail_file_id',
        ),
    ]
