# Generated by Django 3.2 on 2021-06-24 14:09

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_remove_promotion_thumbnail_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Инвайт код'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320.", null=True, upload_to=dashboard.models.lesson_upload_directory, validators=[dashboard.validators.validate_dimensions, dashboard.validators.validate_thumbnail_size], verbose_name='Промо превью'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(help_text='Не больше 50 мб', upload_to=dashboard.models.promo_upload_directory, validators=[dashboard.validators.validate_video_extension, dashboard.validators.validate_file_size], verbose_name='Промо видео'),
        ),
    ]
