# Generated by Django 3.2 on 2021-06-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20210624_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('json_answers', models.TextField(blank=True, null=True, verbose_name='Ответы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='Студент')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
