# Generated by Django 3.2 on 2021-06-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_quizanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='json_answers',
            new_name='answers',
        ),
    ]
