# Generated by Django 3.2 on 2021-06-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_rename_json_answers_quizanswer_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'verbose_name': 'Ответ на викторину', 'verbose_name_plural': 'Ответы на викторину'},
        ),
    ]
