# Generated by Django 3.2 on 2021-07-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20210629_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Заблокировал бота'),
        ),
        migrations.CreateModel(
            name='SendingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('sent', models.IntegerField(default=0, verbose_name='Количетсво отправок')),
                ('received', models.IntegerField(default=0, verbose_name='Получило')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotion', verbose_name='Промо')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
