# Generated by Django 3.2 on 2021-07-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20210706_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Оплатил курс'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='received',
            field=models.IntegerField(default=0, verbose_name='Итого отправлено'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='sent',
            field=models.IntegerField(default=0, verbose_name='Кол-во получателей'),
        ),
    ]
