# Generated by Django 3.2 on 2021-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20210706_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='lang',
            field=models.CharField(choices=[('all', 'Всем'), ('1', 'Russian'), ('2', 'Uzbek')], default='1', max_length=20, verbose_name='Язык отправки'),
            preserve_default=False,
        ),
    ]
