# Generated by Django 3.2 on 2021-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_sendingreport_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к пользователю'),
        ),
    ]
