# Generated by Django 3.2 on 2021-07-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_student_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='celery_id',
            field=models.CharField(default='OLD RECORD', editable=False, max_length=36, verbose_name='Celery group uuid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendingreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Отправляется'), ('DONE', 'Отправлено')], default='PENDING', max_length=50, verbose_name='Статус отправки'),
        ),
    ]
