# Generated by Django 3.2 on 2021-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_alter_sendingreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingreport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус отправки'),
        ),
    ]
