# Generated by Django 3.2 on 2021-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='registration_button',
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_message',
            field=models.TextField(default='ВВЕДИТЕ СООБЩЕНИЕ', verbose_name='Сообщение после регистрации на курс'),
            preserve_default=False,
        ),
    ]
