# Generated by Django 3.2 on 2021-07-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_form_formanswer_formquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='form',
            name='one_off',
            field=models.BooleanField(default=False, verbose_name='Одноразовая форма'),
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Бал')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.form')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
