# Generated by Django 3.2 on 2021-07-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20210714_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='image_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Image ID'),
        ),
    ]
