# Generated by Django 3.2 on 2021-07-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_form_formanswer_formquestion_studentform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentform',
            options={'verbose_name': 'Ответ на форму', 'verbose_name_plural': 'Ответы на форму'},
        ),
        migrations.AddField(
            model_name='studentform',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные'),
        ),
    ]
