# Generated by Django 3.2 on 2021-07-22 10:41

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20210717_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='is_started',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='image_file_id',
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.form_question_directory, verbose_name='Картинка'),
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
    ]
