# Generated by Django 3.2 on 2021-07-22 16:22

from django.db import migrations, models

import dashboard.models
import dashboard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20210722_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end_message',
            field=models.CharField(default='ENTER MESSAGE', max_length=50, verbose_name='Сообщение для отправки при завершении'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_message',
            field=models.CharField(default='ENTER MESSAGE', max_length=50, verbose_name='Сообщение для отправки при старте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320.", null=True, upload_to=dashboard.models.promo_upload_directory, validators=[dashboard.validators.validate_dimensions, dashboard.validators.validate_thumbnail_size], verbose_name='Промо превью'),
        ),
    ]
