# Generated by Django 3.2 on 2021-07-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20210722_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formanswer',
            name='ordering',
        ),
    ]
