# Generated by Django 3.2 on 2021-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_formanswer_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='formquestion',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Нумерация'),
            preserve_default=False,
        ),
    ]
