# Generated by Django 3.2 on 2021-07-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20210726_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentform',
            unique_together={('student', 'form')},
        ),
    ]
