# Generated by Django 3.2 on 2021-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_alter_studentform_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='custom_answer',
            field=models.BooleanField(default=False, verbose_name='Возможность кастомного ответа'),
        ),
    ]
