# Generated by Django 3.2 on 2021-07-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_formquestion_custom_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jumps', to='dashboard.formquestion', verbose_name='Ведет к вопросу'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.formquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='custom_answer',
            field=models.BooleanField(default=False, verbose_name='Кастомный ответ'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл'),
        ),
    ]
