# Generated by Django 3.2 on 2021-07-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_auto_20210728_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Балл')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Ответ на форму',
                'verbose_name_plural': 'Ответы на форму',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.contact', verbose_name='ТГ Профиль'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumps', to='dashboard.formquestion', verbose_name='Ведет к вопросу'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.formquestion', verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
        migrations.AddField(
            model_name='contactform',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.contact'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.form'),
        ),
        migrations.AlterUniqueTogether(
            name='contactform',
            unique_together={('contact', 'form')},
        ),
    ]
