# Generated by Django 3.2 on 2021-07-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20210728_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormAnswers',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ТГ Профиль', 'verbose_name_plural': 'ТГ Профили'},
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.contact', verbose_name='ТГ Профиль'),
        ),
    ]
