# Generated by Django 3.2 on 2021-08-11 14:16

import dashboard.models
import dashboard.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20210809_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='promos/1.jpg', help_text="The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320.", upload_to=dashboard.models.promo_upload_directory, validators=[django.core.validators.validate_image_file_extension], verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='custom_answer_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кастомного ответа'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, help_text='Не больше 50 мб', null=True, upload_to=dashboard.models.promo_upload_directory, validators=[dashboard.validators.validate_video_extension, dashboard.validators.validate_file_size], verbose_name='Промо видео'),
        ),
    ]
