# Generated by Django 3.2 on 2021-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_remove_promotion_video_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end_message',
            field=models.TextField(verbose_name='Сообщение для отправки при завершении'),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_message',
            field=models.TextField(verbose_name='Сообщение для отправки при старте'),
        ),
    ]
