# Generated by Django 3.2 on 2021-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20210813_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='blocked_bot',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
