# Generated by Django 3.2 on 2021-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_auto_20210819_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='custom_answer_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кастомного ответа'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
    ]
