# Generated by Django 3.2 on 2021-08-25 11:56

from django.db import migrations
from django.db.migrations import RunPython


def match_students(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Form = apps.get_model('dashboard', 'Form')

    for form in Form.objects.all():
        form.end_message = f'{{"0-100": "{form.end_message}"}}'
        form.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_auto_20210819_1217'),
    ]

    operations = [
        migrations.RunPython(match_students, RunPython.noop),
    ]
