# Generated by Django 3.2 on 2021-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_auto_20210825_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'ТГ Профиль'), (2, 'Лид'), (3, 'Клиент')], default=3, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='form',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'ТГ Профиль'), (2, 'Лид'), (3, 'Клиент')], default=3, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='form',
            name='end_message',
            field=models.JSONField(default=dict, help_text='Формат: Диапазон (ОТ-ДО). Пример 0-100', verbose_name='Сообщение для отправки при завершении'),
        ),
    ]
