# Generated by Django 3.2 on 2021-09-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_auto_20210907_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название Уч. центра')),
                ('uz_title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Узбекская версия')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
