# Generated by Django 3.2 on 2021-09-07 15:30

from django.db import migrations
from django.db.migrations import RunPython


def create_demo_center(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LearningCentre = apps.get_model('dashboard', 'LearningCentre')

    LearningCentre.objects.create(title='MEGASKILL')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_auto_20210907_1529'),
    ]

    operations = [
        migrations.RunPython(create_demo_center, RunPython.noop),
    ]
