# Generated by Django 3.2 on 2021-09-07 15:36
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_auto_20210907_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='chosen_field',
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
        migrations.AddField(
            model_name='course',
            name='learning_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='dashboard.learningcentre', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='learning_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='dashboard.learningcentre', verbose_name='Желанная отрасль'),
            preserve_default=False,
        ),
    ]
