# Generated by Django 3.2 on 2021-09-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_auto_20210907_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningcentre',
            options={'verbose_name': 'Уч центр', 'verbose_name_plural': 'Уч центры'},
        ),
        migrations.AlterField(
            model_name='student',
            name='learning_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.learningcentre', verbose_name='Желанная отрасль'),
        ),
    ]
