# Generated by Django 3.2 on 2021-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20210908_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcentre',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Поисковое поле'),
        ),
    ]
