# Generated by Django 3.2 on 2021-09-08 10:59

from django.db import migrations
from django.db.migrations import RunPython


def populate_slug(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LearningCentre = apps.get_model('dashboard', 'LearningCentre')

    for lc in LearningCentre.objects.all():
        lc.slug = lc.id
        lc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_learningcentre_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug, RunPython.noop),
    ]
