# Generated by Django 3.2 on 2021-09-09 13:50

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_alter_learningcentre_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to=dashboard.models.asset_directory, verbose_name='Файл')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('access_level', models.IntegerField(choices=[(1, 'ТГ Профиль'), (2, 'Лид'), (3, 'Клиент')], default=3, verbose_name='Доступ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='learningcentre',
            name='link',
            field=models.CharField(blank=True, help_text='При добавлении в боте появится кнопка ссылка', max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='learningcentre',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название Уч центра'),
        ),
        migrations.CreateModel(
            name='ContactAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset', verbose_name='Ассет')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.contact', verbose_name='Студент')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
