# Generated by Django 3.2 on 2021-09-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_auto_20210909_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Ассет', 'verbose_name_plural': 'Ассеты'},
        ),
        migrations.AlterModelOptions(
            name='contactasset',
            options={'verbose_name': 'Ассет студента', 'verbose_name_plural': 'Ассеты студента'},
        ),
        migrations.AlterUniqueTogether(
            name='contactasset',
            unique_together={('contact', 'asset')},
        ),
    ]
