# Generated by Django 3.2 on 2021-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_auto_20210909_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='accept_file',
            field=models.BooleanField(default=False, verbose_name='Принимать файл'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blocked_bot',
            field=models.BooleanField(default=False, editable=False, verbose_name='Блокнул бота'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зареган'),
        ),
    ]
