# Generated by Django 3.2 on 2021-09-14 15:07

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20210913_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='games',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Игры'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Локация'),
        ),
    ]
