# Generated by Django 3.2 on 2021-12-14 16:01

import certificates.utils.uploaders
import certificates.utils.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_coursemedia'),
        ('contacts', '0002_auto_20211019_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('date_coord', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2, validators=[certificates.utils.validators.validate_x_y])),
                ('name_coord', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2, validators=[certificates.utils.validators.validate_x_y])),
                ('template', models.ImageField(upload_to=certificates.utils.uploaders.cert_tmplt_dir, verbose_name='Шаблон')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('generated_cert', models.ImageField(blank=True, null=True, upload_to=certificates.utils.uploaders.cert_upload_dir, verbose_name='Сертификат')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Студент')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certtemplate', verbose_name='Шаблон')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
