# Generated by Django 3.2 on 2021-09-21 12:36

import assets.utils.uploaders
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to=assets.utils.uploaders.asset_directory, verbose_name='Файл')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('access_level', models.IntegerField(choices=[(1, 'ТГ Профиль'), (2, 'Лид'), (3, 'Клиент')], default=3, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Ассет',
                'verbose_name_plural': 'Ассеты',
            },
        ),
        migrations.CreateModel(
            name='ContactAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Ассет')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ассет студента',
                'verbose_name_plural': 'Ассеты студента',
                'unique_together': {('contact', 'asset')},
            },
        ),
    ]
