# Generated by Django 3.2 on 2021-09-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Курс'),
        ),
    ]
