# Generated by Django 3.2 on 2021-09-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_promotion_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('lang', models.CharField(choices=[('all', 'Всем'), ('1', 'Russian'), ('2', 'Uzbek')], max_length=20, verbose_name='Язык отправки')),
                ('sent', models.IntegerField(default=0, verbose_name='Кол-во получателей')),
                ('received', models.IntegerField(default=0, verbose_name='Итого отправлено')),
                ('failed', models.IntegerField(default=0, verbose_name='Не получило')),
                ('celery_id', models.CharField(editable=False, max_length=36, verbose_name='Celery group uuid')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус отправки')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcast.promotion', verbose_name='Промо')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
