# Generated by Django 3.2 on 2021-09-27 15:32

import broadcast.utils.uploaders
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import general.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_promo'),
        ('contacts', '0001_initial'),
        ('broadcast', '0003_sendingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(blank=True, help_text='Не больше 50 мб', null=True, upload_to=broadcast.utils.uploaders.message_media_directory, validators=[general.validators.validate_video_extension, general.validators.validate_file_size], verbose_name='Промо видео')),
                ('image', models.ImageField(blank=True, help_text="\nThe thumbnail should be in JPEG format and less than 200 kB in size. \nA thumbnail's width and height should not exceed 320.\n", null=True, upload_to=broadcast.utils.uploaders.message_media_directory, validators=[django.core.validators.validate_image_file_extension], verbose_name='Картинка')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cсылка')),
                ('delivery_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('delivery_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('delivered', models.BooleanField(verbose_name='Отправлено')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Получатель')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcast.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отправленные сообщения',
                'verbose_name_plural': 'Отправленное сообщение',
            },
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='SendingReport',
        ),
    ]
