# Generated by Django 3.2 on 2021-09-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('users', '0002_remove_student_promo'),
        ('broadcast', '0003_sendingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cсылка')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Кому отправлено')),
            ],
            options={
                'verbose_name': 'Отправленное Сообщение',
                'verbose_name_plural': 'Отправленные Сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='SendingReport',
        ),
    ]
