# Generated by Django 3.2 on 2021-09-24 12:45

import broadcast.utils.uploaders
import django.core.validators
from django.db import migrations, models
import general.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_promo'),
        ('broadcast', '0003_sendingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(blank=True, help_text='Не больше 50 мб', null=True, upload_to=broadcast.utils.uploaders.message_media_directory, validators=[general.validators.validate_video_extension, general.validators.validate_file_size], verbose_name='Промо видео')),
                ('image', models.ImageField(blank=True, help_text="\nThe thumbnail should be in JPEG format and less than 200 kB in size. \nA thumbnail's width and height should not exceed 320.\n", null=True, upload_to=broadcast.utils.uploaders.message_media_directory, validators=[django.core.validators.validate_image_file_extension], verbose_name='Картинка')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
            },
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='SendingReport',
        ),
    ]
