# Generated by Django 3.2 on 2021-10-29 17:59

import broadcast.utils.uploaders
from django.db import migrations, models
import django.utils.timezone
import general.validators


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_auto_20210927_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, help_text='Не больше 50 мб', null=True, upload_to=broadcast.utils.uploaders.message_media_directory, validators=[general.validators.validate_video_extension, general.validators.validate_file_size], verbose_name='Видео'),
        ),
    ]
